version: 2
jobs:
  build_gradle:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gradle-dependencies-{{ checksum "build.gradle" }}
          - v1-gradle-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-gradle-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - persist_to_workspace:
          root: .
          paths:
            - build
  build_webpack:
      docker:
        - image: circleci/node:7.10
      working_directory: ~/repo
      steps:
        - checkout
        - attach_workspace:
            at: ~/repo
        - restore_cache:
            keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
            - v1-node-dependencies-

        - run: npm i

        - save_cache:
            paths:
              - node_modules
            key: v1-node-dependencies-{{ checksum "package.json" }}

        - run: (npm run build && npm run publish)

workflows:
  version: 2
  build:
    jobs:
      - build_gradle
      - build_webpack:
          requires:
            - build_gradle
